export const aboutHeader = 'Discover Our Galactic Restaurant Locations'
export const aboutBody = 'Embark on a culinary journey through the heart of the cosmos! Our enchanting restaurant chain spans the expanse of the Perseus Arm within the Milky Way, promising an extraordinary dining experience at every stop.';
export const aPHeader = 'Alpha Persei Branch:';
export const aPBody = `Indulge in a feast for the senses at our Alpha Persei location, where you'll dine beneath the radiant glow of the brightest star in Perseus. Let the brilliance of Alpha Persei illuminate your palate and your spirit.`;
export const ePHeader = `Eta Persei Branch:`;
export const ePBody = `At our Eta Persei branch, savor a celestial spectacle as two mesmerizing blue-white stars gracefully dance in the night sky. Join us for a captivating dining experience that captures the poetry of the universe.`;
export const algolHeader = `Algol Branch:`;
export const algolBody = `Experience the extraordinary with our Algol branch's limited-time eclipse menu. Feast on delectable dishes while witnessing the celestial choreography of an eclipsing binary star system. It's a gastronomic event that's truly out of this world.`;
export const locationsEnd = `No matter which branch you choose, we promise a journey of enchantment and delight that transcends the ordinary. Join us as we merge culinary artistry with the wonders of the cosmos.`;
export const mapTag = `Locations:`;
export const cIHeader = `Contact Information`;
export const aMail = `📧 Amail: ⏁⊑⟟⋏☌⟟⟟⎐@⏃⋔⏃⟟⍾.⟟⋏⏁`;
export const qECode = `🌌 Q-Entangler Code: 6e122842714736e14bc635ed11f9b42b`;
